### ISSUE TITLE
Gizmo64 locking up X-Plane 11...

### ISSUE THREAD

**Issue by Near76** [benrussell/Gizmo64.com#5]
I am running x-plane 11 on windows 10 with a 6700XT and two G5s from X-Aviation.  When I use OpenGL graphics x-plane operates as expected.  When I enable Vulkan, the screen freezes as soon as the cockpit is in view.  From a clean install (with Vulkan working) and then backing out plugins until I can reproduce it, it appears gizmo64 may be the culprit.  Attached is the log.txt showing what is reported just before it locks up.  If I remove the gizmo64 plugin then all non-G5 planes operate again in Vulkan...of course the G5 based ones do not due to dependencies.  Looking for some help in what may be going on with my setup.  Thank you
[Log.txt](https://github.com/benrussell/Gizmo64.com/files/8306432/Log.txt)
!

**Comment by benrussell** [comment]
Further details for this in forum thread:

https://forums.x-pilot.com/forums/topic/23987-gizmo64-appears-to-be-locking-up-x-plane/#comment-177858

**Comment by benrussell** [comment]
AMD driver fault. Closed.
