### ISSUE TITLE
arm64 Binary

### ISSUE THREAD

**Issue by tstephansen** [benrussell/Gizmo64.com#6]
Sorry if this is the wrong place to make this request (and feel free to just close the issue if that's the case). I was wondering, is it possible to compile the plugin in arm64 for the M1 Macbook Pro? This plugin is the only thing (AFAIK) that's keeping me from running XP12 without Rosetta. Not sure what it's written in but I've actually had quite a bit of luck compiling some old C libs I needed in a work project on the M1.

**Comment by benrussell** [comment]
Hi Tim.

There is a public beta Arm build to be found here:
https://blog.x-plugins.com/2023/02/gizmo64-version-23.html

Thanks for your patience and your bug report.
Ben

**Comment by tstephansen** [comment]
Thanks, Ben!
