### ISSUE TITLE
Question - how to use UDP send / receive from Gizmo64

### ISSUE THREAD

**Issue by samthesuperhero** [benrussell/Gizmo64.com#7]
Hello,

can you pls advise the way to establish the UDP communication with Gizmo64 script ?

**Comment by benrussell** [comment]
There is currently no way to access raw UDP sockets from Gizmo... Would luasocket be useful in the future?

https://github.com/lunarmodules/luasocket

**Comment by samthesuperhero** [comment]
> There is currently no way to access raw UDP sockets from Gizmo... Would luasocket be useful in the future?
> 
> https://github.com/lunarmodules/luasocket

Sure, rather useful for integrations with custom hw, for homemade cockpits.

Thanks!!
