### ISSUE TITLE
Not compatible with X-Plane 12 for ARM Mac computers

### ISSUE THREAD

**Issue by jipvankuijk** [benrussell/Gizmo64.com#8]
Hey there,

Gizmo64 only works when running the x-plane 12 application in Rosetta mode. Sadly this means that I can't run the simulator natively with any add-on airplanes that need Gizmo. 

It would be cool if Gizmo could be made ARM compatible.

**Comment by benrussell** [comment]
https://blog.x-plugins.com/2023/02/gizmo64-version-23.html
